# cf. https://jsr.io/@core/unknownutil/3.18.1/.github/workflows/jsr.yml
name: publish

env:
  DENO_VERSION: 2.x

on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Publish on tag
        run: deno task publish
